### ISSUE TITLE
Agreements for using syntax file for vscode

### ISSUE THREAD

**Issue by mattn** [bradrobertson/sublime-packages#3]
Currently, vscode doesn't support lisp syntax. So I want to provide extension vscode-lisp for enabling syntax on vscode. Then, I want to use your syntaxes/Lisp.tmLanguage on my extension. Do you have something that I should follow the rules or license matter? I will put the author/link to your's into the README file. Regards.

**Comment by bradrobertson** [comment]
Oh wow, I don't even remember this repo or where this code originally came from. You can take whatever you want from here as I'm not even the original author either.

**Comment by mattn** [comment]
Thank you. https://marketplace.visualstudio.com/items?itemName=mattn.lisp
